name Web API Deploy Pipeline
on:
  push
    paths:
      - '.github/workflows/**'
      - 'api-demo/**'

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: Tokushige1
  ECS_SERVICE: Tokushige1-service1
  ECR_REPOSITORY: tokushige1
  ECS_TASK_DEFINITION_API: api-demo/.aws/task-def-api.json

permissions:
  id-token: write
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: api-demo
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests and Build an Image
        run: docker image build -t temp_api_inage:latest .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_ROLE_TO_ASSUME}}

      - name Login to Amazon ECR
        id: login-ECR
        uses: aws-actions/amazon-ecr-login@v2
      
      - name Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
        run:
          docker image tag temp_api_image:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{github.sha}}
          docker image push $ECR_REGISTRY/$ECR_REPOSITORY:${{github.sha}}
